name: Ball66

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *" # 🇹🇭 19:00 ทุกวัน

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repo
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm" # 🔥 เร็วขึ้น

      - name: 📦 Install dependencies
        run: npm install

      - name: 🚀 Run scraper
        run: node ball66.js

      - name: 💾 Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git add playlist.json playlist.m3u

          # 🔥 เช็คว่ามีการเปลี่ยนจริงไหม
          if git diff --cached --quiet; then
            echo "No changes"
          else
            git commit -m "🔄 auto update playlist"
            git push
          fi
