name: RY

on:
  workflow_dispatch:
  schedule:
    - cron: "0 */12 * * *"

concurrency:
  group: ry-scraper
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm install
      - run: node ry2.js

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "update data" || echo "no changes"
          git pull --rebase
          git push
