name: RY
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run Scraper
        run: node ry2.js
      - name: Commit JSON
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add *.json
          git commit -m "Update playlists" || echo "No changes"
          git push
