name: RY
on:
  push:
    branches: [ main ]
  workflow_dispatch:

  schedule:
    - cron: "0 15 * * *" # ทุก 6 ชั่วโมง

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install Dependencies
        run: npm install
      - name: Run Scraper
        run: node ry2.js
      - name: Commit JSON
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .
          git commit -m "update data" || echo "no changes"
          git push
