name: Anime108

on:
  workflow_dispatch:
  schedule:
    - cron: "0 15 * * *" # ทุกวัน 22:00 ไทย

permissions:
  contents: write

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      # 1. โหลด repo
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Node
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3. ติดตั้ง package
      - name: Install dependencies
        run: npm install axios cheerio

      # 4. รัน
      - name: Run scraper
        run: node anime108.js

      # 5. push แบบปลอดภัย
      - name: Push changes
        run: |
          git config --global user.name "bot"
          git config --global user.email "bot@users.noreply.github.com"
          git add .

          git commit -m "update data" || echo "no changes"

          # 🔥 ปลอดภัยกว่า rebase
          git pull origin main --no-rebase || echo "no remote changes"

          git push origin HEAD:main
